---
- hosts: lb
  become: 'yes'
  tasks:
    - apt: name=nginx state=present
    - name: Remove default.conf
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent

    - name: Loop template
      template:
        src: server.conf.j2
        dest: /etc/nginx/conf.d/{{ item.server_name }}.conf
      vars:
        listen: "{{ item.server_port }}"
        server_name: "{{ item.server_name }}"
        locations: "{{ item.locations }}"

      loop:
        - server_port: 7070
          server_name: jmart-ansible.kz
          locations:
          - path: /main
            status_code: 200
            message: Добро пожаловать на JMart!
          - path: /profile
            status_code: 201
            message: Это страница профиля.

        - server_port: 8080
          server_name: jusan-ansible.kz
          locations:
            - path: /
              status_code: 200
              message: Добро пожаловать на Jusan Bank!
            - path: /account
              status_code: 202
              message: Здесь ваш банковский счет!

        - server_port: 9090
          server_name: invest-ansible.kz
          locations:
            - path: /home
              status_code: 200
              message: Добро пожаловать на Jusan Invest!
            - path: /user
              status_code: 203
              message: Это страница c вашим брокерским счетом.
    - name: nginx Start
      service:
        name: nginx
        state: reloaded